name: ck-builder
run-name: cm-${{ inputs.variant }}-${{ inputs.platform }}

on:
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Please select a build variant
        default: brew
        required: true
        options: 
          - brew
          - native
          - universal
          - full
          - nomp3
          - light
      platform:
        type: choice
        description: Please select a supported platform
        default: macos-latest
        required: true
        options: 
          - macos-14
          - macos-13
          - macos-12
          - windows-2022
          - windows-2019

# env:
#   arch: darwin-x86

jobs:
  build:
    runs-on: ${{ inputs.platform }}

    steps:

    - name: job information
      run: |
        echo "OS Version: `uname -v`"
        echo "MacOS SDK Platform Version: `xcrun --show-sdk-platform-version`"

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 7

    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v4
      env:
        cache-name: ck-cache-1
      with:
        path: build/thirdparty/downloads
        key: $${{ env.cache-name }}-${{ hashFiles('source/scripts/dep/install_libfaust.sh') }}

    - name: install chuck dependencies
      run: brew install bison flex

    - name: install faust + warpbuf (libsndfile) dependencies
      if: contains(fromJSON('["brew", "full", "light", "nomp3"]'), inputs.variant)
      run: brew install autogen automake flac libogg libvorbis opus mpg123 lame

    - name: install warpbuf (rubberband) dependencies
      if: contains(fromJSON('["brew", "full", "light", "nomp3"]'), inputs.variant)
      run: brew install rubberband libsamplerate

    - name: build external
      run: make ${{ inputs.variant }}

    - name: create package for distribution
      run: make package

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ inputs.variant }}-${{ runner.os }}-${{ runner.arch }}-${{ env.SHA }}
        path: build/dist/${{ github.event.repository.name }}

