name: ck-builder

on:
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Please select a build variant
        default: full
        required: true
        options: 
          - full
          - light
          - base

env:
  arch: darwin-x86

jobs:
  build:
    runs-on: macos-latest
    # runs-on: macos-11 # requires changes

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7

    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v3
      env:
        cache-name: ck-cache-1
      with:
        path: build/downloads
        key: $${{ env.cache-name }}-${{ hashFiles('source/scripts/install_deps.sh') }}

    - name: install dependencies
      run: brew update && brew install bison flex

    - name: install libsndfile dependencies
      run: brew install autoconf autogen automake flac libogg libtool libvorbis opus mpg123 pkg-config

    - name: build external
      run: make ${{ github.event.inputs.variant }}

    # - name: install faust
    #   run: source/scripts/dep/install_faust.sh

    # - name: install libfaust
    #   run: source/scripts/dep/install_libfaust.sh

    # - name: install libflac
    #   run: source/scripts/dep/install_libflac.sh

    # - name: install libogg
    #   run: source/scripts/dep/install_libogg.sh

    # - name: install libopus
    #   run: source/scripts/dep/install_libopus.sh

    # - name: install libsamplerate
    #   run: source/scripts/dep/install_libsamplerate.sh

    # - name: install libvorbis
    #   run: source/scripts/dep/install_libvorbis.sh

    # - name: install rubberband
    #   run: source/scripts/dep/install_rubberband.sh

    # - name: install libmp3lame
    #   run: source/scripts/dep/install_libmp3lame.sh

    # - name: install libmpg123
    #   run: source/scripts/dep/install_libmpg123.sh

    # - name: Build externals
    #   run: make ${{ github.event.inputs.variant }}

    # - name: install libsndfile
    #   run: source/scripts/dep/install_libsndfile.sh

    - uses: actions/upload-artifact@v4
      with:
        name: chuck-max
        path: |
          examples
          externals
          help
          patchers
          CHANGELOG.md
          LICENSE
          package-info.json
          README.md

