name: ck-builder

on:
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Please select a build variant
        default: brew
        required: true
        options: 
          - brew
          - native
          - universal
          - full
          - light

env:
  arch: darwin-x86

jobs:
  build:
    runs-on: macos-latest

    steps:

    - name: set the architecture pf the build
      if: contains(fromJSON('["brew", "full", "light"]'), github.event.inputs.variant)
      run: echo "arch=darwin-x86" >> "$GITHUB_ENV"

    - name: set the architecture pf the build
      if: contains(fromJSON('["universal"]'), github.event.inputs.variant)
      run: echo "arch=universal" >> "$GITHUB_ENV"

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 7

    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v4
      env:
        cache-name: ck-cache-1
      with:
        path: build/thirdparty/downloads
        key: $${{ env.cache-name }}-${{ hashFiles('source/scripts/dep/install_libfaust.sh') }}

    - name: install chuck dependencies
      run: brew install bison flex

    - name: install faust + warpbuf (libsndfile) dependencies
      if: contains(fromJSON('["brew", "full", "light"]'), github.event.inputs.variant)
      run: brew install autoconf autogen automake flac libogg libtool libvorbis opus mpg123 lame

    - name: install warpbuf (rubberband) dependencies
      if: contains(fromJSON('["brew", "full", "light"]'), github.event.inputs.variant)
      run: brew install rubberband libsamplerate

    - name: build external
      run: make ${{ github.event.inputs.variant }}

    - name: create package for distribution
      run: make package

    - uses: actions/upload-artifact@v4
      with:
        # name: ${{ github.event.repository.name }}-${{ github.event.inputs.variant }}-${{ env.arch }}-${{ env.SHA }}
        name: ${{ github.event.repository.name }}-${{ github.event.inputs.variant }}-$arch-${{ env.SHA }}
        path: build/dist/${{ github.event.repository.name }}.zip

