name: ck-brew-builder

env:
  arch: darwin-x86

jobs:
  build:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 7

    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v4
      env:
        cache-name: ck-cache-1
      with:
        path: build/thirdparty/downloads
        key: $${{ env.cache-name }}-${{ hashFiles('source/scripts/dep/install_libfaust.sh') }}

    - name: install chuck dependencies
      run: brew install bison flex

    - name: install faust + warpbuf (libsndfile) dependencies
      run: brew install autoconf autogen automake flac libogg libtool libvorbis opus mpg123 lame

    - name: install warpbuf (rubberband) dependencies
      run: brew install rubberband libsamplerate

    - name: build external
      run: make brew

    - uses: actions/upload-artifact@v4
      with:
        name: chuck-max-${{ env.arch }}-${{ env.SHA }}
        path: |
          examples
          externals
          help
          patchers
          CHANGELOG.md
          LICENSE
          package-info.json
          README.md
