name: ck-info
run-name: info-${{ runner.arch }}-${{ inputs.platform }}


on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: Please select a supported platform
        default: macos-latest
        required: true
        options: 
          - macos-latest
          - macos-13
          - macos-12
          # - windows-latest

jobs:
  build:
    runs-on: ${{ inputs.platform }}

    steps:

    - name: runner information
      run: |
        echo "image: ${{ inputs.platform }}"
        echo "arch: `uname -m`"
        echo "runner.os: ${{ runner.os }}"
        echo "runneer.arch: ${{ runner.arch }}"
