name: ck-matrix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-14
          - macos-13
          - macos-12
        variant:
          - native
          - universal
          - brew
          - full
          - nomp3
          - light

# env:
#   arch: darwin-x86

    steps:

    - name: job information
      run: |
        echo "OS Version: `uname -v`"
        echo "MacOS SDK Platform Version: `xcrun --show-sdk-platform-version`"

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 7

    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v4
      env:
        cache-name: ck-cache-1
      with:
        path: build/thirdparty/downloads
        key: $${{ env.cache-name }}-${{ hashFiles('source/scripts/dep/install_libfaust.sh') }}

    - name: install chuck dependencies
      run: brew install bison flex

    - name: install faust + warpbuf (libsndfile) dependencies
      if: contains(fromJSON('["brew", "full", "light"]'), matrix.variant)
      run: brew install autoconf autogen automake flac libogg libtool libvorbis opus mpg123 lame

    - name: install warpbuf (rubberband) dependencies
      if: contains(fromJSON('["brew", "full", "light"]'), matrix.variant)
      run: brew install rubberband libsamplerate

    - name: build external
      run: make ${{ matrix.variant }}

    - name: create package for distribution
      run: make package

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.variant }}-${{ matrix.os }}-${{ runner.arch }}-${{ env.SHA }}
        path: build/dist/${{ github.event.repository.name }}

